---
title: "决策树算法应用"
author: "虹"
date: '2023-05-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## heart(心脏病数据集)
```{r}
library(readxl)
heart_data <- read.csv("heart.csv")
#View(heart_data)
library(rpart)
library(rpart.plot) #nolint
# 加载 caret 包
library(caret) ##可用于特征工程

# 将数据集划分为训练集和测试集
set.seed(123) # 设置随机数种子，以确保结果可重复

train_index <- createDataPartition(heart_data$target,p=0.8,list=FALSE) 

train_data <- heart_data[train_index,] # 训练集
test_data <- heart_data[-train_index,] # 测试集
# View(test_data)
# 训练决策树
my_tree <- rpart(target~.,data = train_data,method ="class")
# print(my_tree)
y_pre <- predict(my_tree,test_data[,1:(ncol(test_data)-1)],type="class")
# print(y_pre)
rpart.plot(my_tree)
## 计算精度
confusion_matrix <- confusionMatrix(y_pre,factor(test_data$target,levels = c(0,1)))
print(confusion_matrix)
```


## 电离层数据集
```{r}
library(pROC)
ionosphere_train <- read_excel("ionosphere_train.xlsx")
ionosphere_test <- read_excel("ionosphere_test.xlsx")
# View(ionosphere_test)
myTree <- rpart(target~.,data = ionosphere_train,method = "class") # nolint
# print(myTree)
y_pre <- predict(myTree,ionosphere_test[,1:(ncol(ionosphere_test)-1)],type="class")
# print(y_pre)
rpart.plot(myTree)

## 模型的评价
confusion_matrix <- confusionMatrix(y_pre,factor(ionosphere_test$target,levels = c("b","g")))
print(confusion_matrix)
roc_data <- roc(as.numeric(y_pre),as.numeric(factor(ionosphere_test$target,levels = c("b","g"))))
plot(roc_data)
```



